workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/Web-Admin-TreeDPlant

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo npm install
      - run: sudo npm run build

